- alias: wallboxWatchDog
  description: 'Write to wallbox register to avoid comm error'
  trigger:
  - platform: time_pattern
    seconds: "/10"
  condition: []
  action:
  - service: modbus.write_register
    data:
      slave: 1
      address: 258
      value: 4
      hub: wallbox